sudo: required
services: docker
language: minimal

script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/bin
  - docker-compose run airflow-testing
